apiVersion: v1
kind: Service
metadata:
  name: iotex-service
  labels:
    app: iotex-service
spec:
  ports:
  - port: 4689
    name: iotex-network
  - port: 14014
    name: iotex-api
  - port: 8080
    name: iotex-stats
  selector:
    app: iotex
  type: LoadBalancer
  loadBalancerIP: [your ip]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iotex
spec:
  selector:
    matchLabels:
      app: iotex

  serviceName: iotex-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iotex
    spec:
      containers:
      - name: iotex-core
        image: iotex/iotex-core:v0.5.0-rc6
        command:
        - iotex-server
        - -config-path=/etc/iotex/config.yaml
        - -genesis-path=/etc/iotex/genesis.yaml
        - -plugin=gateway
        ports:
        - containerPort: 4689
          name: iotex-network
        - containerPort: 14014
          name: iotex-api
        - containerPort: 8080
          name: iotex-stats
        volumeMounts:
        - mountPath: /etc/iotex
          name: config-volume
        - mountPath: /var/data
          name: data-volume
          subPath: data
        - mountPath: /var/log
          name: data-volume
          subPath: log
      volumes:
      - configMap:
          name: iotex-mainnet-config
        name: config-volume
      - name: data-volume
        hostPath:
          path: /var/iotex
          type: DirectoryOrCreate